version: '3.9'
services:

    django:
        build: .
        ports:
            - '8000:8000'
        command: >
            sh -c "python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
        depends_on:
            -   redis


    redis:
        image: redis:alpine
        ports:
            - '6379:6379'